### ISSUE TITLE
codegen: signed_extensions in metadata v14 breaks codegen

### ISSUE THREAD

**Issue by niklasad1** [paritytech/subxt#1285]
In staking miner when I tried to upgraded subxt from v0.29 to v0.31 then the codegen broke for some reason which I don't understand. Just to clarify this metadata was trimmed and only two pallets were generated.

Then I had to update the metadata to work and I don't really understand why but the metadata breaks things can be found here: 
https://github.com/paritytech/staking-miner-v2/blob/v1.1.0/artifacts/metadata.scale

```
error: Could not decode metadata, only V14 and V15 metadata are supported: Could not decode `RuntimeMetadataPrefixed.1`:
           Could not decode `RuntimeMetadata::V15.0`:
               Could not decode `RuntimeMetadataV15::extrinsic`:
                   Could not decode `ExtrinsicMetadata::signed_extensions`:
                       out of range decoding Compact<u32>
  --> src/prelude.rs:67:1
   |
67 | / #[subxt::subxt(
68 | |     runtime_metadata_path = "artifacts/metadata.scale",
69 | |     derive_for_all_types = "Clone, Debug, Eq, PartialEq",
70 | |     derive_for_type(
...  |
81 | |     )
82 | | )]
   | |__^
   |
   = note: this error originates in the attribute macro `subxt::subxt` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: use of undeclared crate or module `runtime`
   --> src/commands/monitor.rs:556:19
    |
556 |                 .find_first::<runtime::election_provider_multi_phase::events::SolutionStored>(
    |                               ^^^^^^^ use of undeclared crate or module `runtime`

```

**Comment by jsdw** [comment]
Thanks for the report! I feel like we've had a couple of issues in this area, partly because the current polkadot runtime (last I checked at least) supported V14 and "unstable V15 which isn't quite right so we can't decode it". I've see nthat specific error message when you give the unstable V15 metadata to Subxt for instance.

My only suggestion offhand is to try asking specifically for V14 (or V15 is available by now) metadata when using the CLI tool to download and see if that helps, jsut incase you're fetching unstable or something!

**Comment by jsdw** [comment]
Ah, if it's old then unless it was explicitly unstable metadata (eg because you wanted to try runtime APIs or whatever) it should still work!

**Comment by niklasad1** [comment]
Nah, exactly the same code without any v15 features was tried and it worked fine with subxt v0.29 but with subxt v0.31 then the codegen broke which the error above.

Yeye, it's possible that your refactoring broke how the metadata is generated/parsed by the subxt-cli.
It's probably fine anyway it should just work be "re-generating" the metadata with the subxt-cli tool

**Comment by jsdw** [comment]
Ah, well Subxt 0.29 supported the unstable V15 metadata, and just before the metadata was stabilised a couple of small last min changes went in, so my geuss is that your `metadata.scale` is the old "unstable" format which 0.29 worked with and versions after that didn't work with because they updated to decode the proper stable V15 instead :)

In the proc macro you can't tell it to use a particular version (mainly you should be loading from a file anyway so it has no choice, and if you're loading from a URL then right now there's nothing meaningful you can tell it to do and it'll download latest stable from a node)

**Comment by niklasad1** [comment]
Gotcha, I'm to close this issue partly my own fault then but hopefully the issue itself may help others
